name: VisionMamba
channels:
  - nvidia/label/cuda-11.8.0
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - attr=2.5.2
  - binutils=2.44
  - binutils_impl_linux-64=2.44
  - binutils_linux-64=2.44
  - bzip2=1.0.8
  - c-compiler=1.11.0
  - ca-certificates=2025.10.5
  - conda-gcc-specs=14.3.0
  - cuda-cccl_linux-64=13.0.85
  - cuda-command-line-tools=13.0.2
  - cuda-compiler=11.8.0
  - cuda-crt-dev_linux-64=13.0.88
  - cuda-crt-tools=13.0.88
  - cuda-ctadvisor=13.0.85
  - cuda-cudart=13.0.96
  - cuda-cudart-dev=13.0.96
  - cuda-cudart-dev_linux-64=13.0.96
  - cuda-cudart-static=13.0.96
  - cuda-cudart-static_linux-64=13.0.96
  - cuda-cudart_linux-64=13.0.96
  - cuda-cuobjdump=13.0.85
  - cuda-cupti=13.0.85
  - cuda-cupti-dev=13.0.85
  - cuda-cuxxfilt=13.0.85
  - cuda-documentation=11.8.86
  - cuda-driver-dev=13.0.96
  - cuda-driver-dev_linux-64=13.0.96
  - cuda-gdb=13.0.85
  - cuda-libraries=13.0.2
  - cuda-libraries-dev=13.0.2
  - cuda-nsight=13.0.85
  - cuda-nvcc=11.8.89
  - cuda-nvcc-dev_linux-64=13.0.88
  - cuda-nvcc-impl=13.0.88
  - cuda-nvcc-tools=13.0.88
  - cuda-nvcc_linux-64=13.0.88
  - cuda-nvdisasm=13.0.85
  - cuda-nvml-dev=13.0.87
  - cuda-nvprune=13.0.85
  - cuda-nvrtc=13.0.88
  - cuda-nvrtc-dev=13.0.88
  - cuda-nvtx=13.0.85
  - cuda-nvvm-dev_linux-64=13.0.88
  - cuda-nvvm-impl=13.0.88
  - cuda-nvvm-tools=13.0.88
  - cuda-opencl=13.0.85
  - cuda-opencl-dev=13.0.85
  - cuda-profiler-api=13.0.85
  - cuda-sanitizer-api=13.0.85
  - cuda-toolkit=11.8.0
  - cuda-tools=13.0.2
  - cuda-version=13.0
  - cuda-visual-tools=13.0.2
  - cxx-compiler=1.11.0
  - dbus=1.16.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - gcc=14.3.0
  - gcc_impl_linux-64=14.3.0
  - gcc_linux-64=14.3.0
  - gds-tools=1.15.1.6
  - gmp=6.3.0
  - gxx=14.3.0
  - gxx_impl_linux-64=14.3.0
  - gxx_linux-64=14.3.0
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libcap=2.76
  - libcublas=13.1.0.3
  - libcublas-dev=13.1.0.3
  - libcufft=12.0.0.61
  - libcufft-dev=12.0.0.61
  - libcufile=1.15.1.6
  - libcufile-dev=1.15.1.6
  - libcurand=10.4.0.35
  - libcurand-dev=10.4.0.35
  - libcusolver=12.0.4.66
  - libcusolver-dev=12.0.4.66
  - libcusparse=12.6.3.3
  - libcusparse-dev=12.6.3.3
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=14.3.0
  - libgcc-ng=15.2.0
  - libgcrypt-lib=1.11.1
  - libglib=2.86.0
  - libglvnd=1.7.0
  - libgomp=15.2.0
  - libgpg-error=1.55
  - libiconv=1.18
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnl=3.11.0
  - libnpp=13.0.1.2
  - libnpp-dev=13.0.1.2
  - libnsl=2.0.1
  - libnuma=2.0.18
  - libnvfatbin=13.0.85
  - libnvfatbin-dev=13.0.85
  - libnvjitlink=13.0.88
  - libnvjitlink-dev=13.0.88
  - libnvjpeg=13.0.1.86
  - libnvjpeg-dev=13.0.1.86
  - libnvptxcompiler-dev=13.0.88
  - libnvptxcompiler-dev_linux-64=13.0.88
  - libopengl=1.7.0
  - libpng=1.6.50
  - libsanitizer=14.3.0
  - libsqlite=3.50.4
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=14.3.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=257.9
  - libudev1=257.9
  - libuuid=2.41.2
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.12.2
  - libxkbfile=1.1.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - ncurses=6.5
  - nsight-compute=2025.3.1.4
  - nspr=4.37
  - nss=3.117
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openssl=3.5.4
  - pcre2=10.46
  - pthread-stubs=0.4
  - python=3.10.13
  - rdma-core=59.0
  - readline=8.2
  - sysroot_linux-64=2.34
  - tk=8.6.13
  - wayland=1.24.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zstd=1.5.7
  - pip:
      - addict==2.4.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - alembic==1.13.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - blinker==1.7.0
      - captum==0.8.0
      - causal-conv1d==1.4.0
      - certifi==2023.11.17
      - cffi==2.0.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - comm==0.2.3
      - contourpy==1.2.0
      - cycler==0.12.1
      - databricks-cli==0.18.0
      - datasets==2.14.5
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.3.7
      - docker==6.1.3
      - einops==0.7.0
      - entrypoints==0.4
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.13.1
      - flask==3.0.0
      - fonttools==4.46.0
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - grad-cam==1.5.5
      - greenlet==3.0.2
      - gunicorn==21.2.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.19.4
      - idna==3.6
      - importlib-metadata==7.0.0
      - ipykernel==7.0.1
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.19.2
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.5
      - lark==1.3.0
      - mako==1.3.0
      - mamba-ssm==1.1.1
      - mambalrp==0.1.0
      - markdown==3.5.1
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - mlflow==2.9.1
      - mmcv==1.3.8
      - mmsegmentation==0.14.1
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.13.0
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numpy==1.26.2
      - oauthlib==3.2.2
      - opencv-python==4.8.1.78
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.1.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==10.1.0
      - pip==23.2.1
      - platformdirs==4.1.0
      - prettytable==3.9.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - protobuf==4.25.1
      - psutil==7.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==14.0.1
      - pyarrow-hotfix==0.6
      - pycparser==2.23
      - pygments==2.19.2
      - pyjwt==2.8.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-hostlist==1.23.0
      - python-json-logger==4.0.0
      - pytoolconfig==1.3.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==27.1.0
      - querystring-parser==1.2.4
      - referencing==0.37.0
      - regex==2023.10.3
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rope==1.14.0
      - rpds-py==0.28.0
      - safetensors==0.4.1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - send2trash==1.8.3
      - setuptools==63.4.3
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.23
      - sqlparse==0.4.4
      - stack-data==0.6.3
      - sympy==1.12
      - tabulate==0.9.0
      - terminado==0.18.1
      - threadpoolctl==3.2.0
      - timm==0.4.12
      - tinycss2==1.4.0
      - tokenizers==0.19.1
      - tomli==2.0.1
      - torch==2.1.1+cu118
      - torchaudio==2.1.1+cu118
      - torchvision==0.16.1+cu118
      - tornado==6.5.2
      - tqdm==4.66.1
      - traitlets==5.14.3
      - transformers==4.40.1
      - triton==2.1.0
      - ttach==0.0.3
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==2.1.0
      - wcwidth==0.2.12
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - wheel==0.40.0
      - widgetsnbextension==4.0.14
      - xxhash==3.4.1
      - yapf==0.40.2
      - yarl==1.9.4
      - zipp==3.17.0
prefix: /home/gian/anaconda3/envs/VisionMamba
